deployment:
  tasks:
    - /bin/rm -rf /home/jummwqdg/public_html/*
    - cd /home/usuario/repositories/cortinasHpuseDeco
    - npm install
    - npm run build
    - /bin/cp -R dist/* //home/jummwqdg/public_html/
