deployment:
  tasks:
    - /bin/rm -rf /home/jummwqdg/public_html/*
    - cd /home/jummwqdg/repositories/cortinasHpuseDeco
    - /opt/alt/alt-nodejs20/root/usr/lib/node_modules/npm/bin/npm install
    - /opt/alt/alt-nodejs20/root/usr/lib/node_modules/npm/bin/npm run build
    - /bin/cp -R build/* /home/jummwqdg/public_html/
